#%RAML 1.0
---
title: Toonami Ratings API
#baseUri: http://jukebox.api.com
baseUri: http://toonamiratings.com
version: v1

types:
    show: !include schemas/show.schema

resourceTypes:
    readOnlyCollection:
        description: |
             Collection of available <<resourcePathName>> for toonami ratings.
        get:
            description: Get a list of <<resourcePathName>>.
            responses:
                200:
                    body:
                        application/json:
                            example: |
                                <<exampleCollection>>
